title: PMII Sepuluh Nopember
description: Website resmi PMII Sepuluh Nopember
baseurl: "/pmii1011"
url: "https://azharanas17.github.io"

theme: minima

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:title/

collections:
  posts:
    output: true